server {
    listen 80;
    server_name groenendaal.ddns.net;

    location /example_app/api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host ;
        proxy_set_header X-Real-IP ;
    }

    location /example_app/ {
        proxy_pass http://frontend:3000/;
        proxy_set_header Host ;
        proxy_set_header X-Real-IP ;
        proxy_http_version 1.1;
        proxy_set_header Upgrade ;
        proxy_set_header Connection 'upgrade';
    }
}
